version: '3'

services:

  web:
    build: '.'
    environment:
      FLASK_DEBUG: '1'
      PRIMARY_USER: ${PRIMARY_USER}
      CLIENT_SECRET_FILE: ${CLIENT_SECRET_FILE}
      MASTER_DOC_ID: ${MASTER_DOC_ID}
      MASTER_SPREADSHEET_ID: ${MASTER_SPREADSHEET_ID}
    volumes:
      - './src:/srv/src'
    ports:
      - '8080:8080'
