version: '3'

services:

  webapp:
    container_name: tax_planner
    labels:
      shipyard.route: '/'
    build: '.'
    environment:
      FLASK_ENV: ${ENVIRONMENT}
      PRIMARY_USER: ${PRIMARY_USER}
      CLIENT_SECRET_FILE: ${CLIENT_SECRET_FILE}
      MASTER_DOC_ID: ${MASTER_DOC_ID}
      MASTER_SPREADSHEET_ID: ${MASTER_SPREADSHEET_ID}
      MASTER_FOLDER_ID: ${MASTER_FOLDER_ID}
      CLIENT_FOLDER_ID: ${CLIENT_FOLDER_ID}
    volumes:
      - './src:/srv/src'
    ports:
      - '8080:8080'
