from .input_fields import (
    BASIC_INFO,
    FEDERAL_INCOME,
    FEDERAL_INCOME_ADJUSTMENTS,
    BUSINESS_INCOME,
    FEDERAL_DEDUCTIONS,
    ESTIMATED_TAX_PAYMENTS,

    STATES,
    FILING_STATUSES,
    INDUSTRIES,

    MASTER_SPREADSHEET_RANGES
)

__all__ = [
    b'BASIC_INFO',
    b'FEDERAL_INCOME',
    b'FEDERAL_INCOME_ADJUSTMENTS',
    b'BUSINESS_INCOME',
    b'FEDERAL_DEDUCTIONS',
    b'ESTIMATED_TAX_PAYMENTS',
    b'STATES',
    b'FILING_STATUSES',
    b'INDUSTRIES',
    b'MASTER_SPREADSHEET_RANGES'
]
