from .input_fields import (
    BASIC_INFO,
    FEDERAL_INCOME,
    FEDERAL_INCOME_ADJUSTMENTS,
    BUSINESS_INCOME,
    FEDERAL_DEDUCTIONS,
    ESTIMATED_TAX_PAYMENTS
)

__all__ = [
    b'BASIC_INFO',
    b'FEDERAL_INCOME',
    b'FEDERAL_INCOME_ADJUSTMENTS',
    b'BUSINESS_INCOME',
    b'FEDERAL_DEDUCTIONS',
    b'ESTIMATED_TAX_PAYMENTS'
]
